### PR TITLE
Rw nutshell events

### PR DESCRIPTION
**Pull request by rosewisotzky**
# Description

I created the add new event button and save button . I also created the input fields for new event name, location, and date. Event listeners were added to both buttons to listen for a click and console log a message showing that they work.

Applies to issue # Events .05

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions

1. `git fetch`
2. `git checkout rw-nutshell-events` 
3. If you already have a reference to this branch, run `git pull origin rw-nutshell-events` to get updates to code.
4. cd into src/lib and run grunt
5. open browser and go to http:localhost:8080
6. verify all forms are appending to the dom and that console log displays messages when buttons are clicked.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by SamBritt** [comment]
Fix trailing spaces! cannot run Grunt

**Review by SamBritt — DISMISSED** [review]
It works!

**Review by greenskybluephish — APPROVED** [review]
i tested it and it works. will integrate perfectly

**Review by SamBritt — APPROVED** [review]
Awesome

**Pull request merged**
