### PR TITLE
Newb

### PR DESCRIPTION
**Pull request by greenskybluephish**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Issue #1 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Testing Instructions
Git fetch and checkout branch. Create new file with .example removed from database.json file. 
run grunt to test json server. 
 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by greenskybluephish** [comment]
just updated database.json

**Comment by rosewisotzky** [comment]
Lookin' good brother

**Review by SamBritt — APPROVED** [review]
Looks good 💯

**Review by rosewisotzky — APPROVED** [review]
round 2 of approval

**Pull request merged**
