### PR TITLE
Sb task to dom

### PR DESCRIPTION
**Pull request by SamBritt**
# Description

Created event handler logic:
When the user clicks the Save button,
values are taken from the task input fields.
Those input fields are stored into an object written in APIStructure.js.
The task object is inserted into a `POST` request, inserting it into our JSON database.
In domAppender.js, a loop is executed, calling the buildTaskComponent function
which creates an HTML structure for each key/value entered into the task input fields.
After the loop is finished, the final list of HTML elements containing Task Name's and Date's is appended to the DOM.
`ClearElement()` is used to wipe the DOM clean, allowing the new task HTML element to be displayed.

Also fixed setting the ID attribute in `constructor.js` to set the HTML attribute to `id` instead `class`.

Applies to issue # (issue number)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Testing Instructions

1. In the terminal, `git fetch`
2. `git checkout -b 'sb-task-to-DOM'`
4. If you have a previously stored local version, run `git pull origin sb-task-to-DOM`
3. `cd` into `src/lib`
4. run `grunt`
5. Enter values into input fields
6. Hit `Submit` button
7. The new task should display on top of previously added tasks

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by wemitchell3** [comment]
I have reviewed and tested your commit. Input fields and save buttons works, writes to json and dom.

Looks good to me.

**Review by rosewisotzky — DISMISSED** [review]
Looks good bud, just gotta comment that code.

**Comment by wemitchell3** [comment]
Actually...Rose is right. You should go ahead and comment your code.
Blame it on Rose.

**Review by wemitchell3 — COMMENTED** [review]
Comments look good. Good to merge.

**Review by wemitchell3 — DISMISSED** [review]
Comments look good. Good to merge.

**Review by greenskybluephish — DISMISSED** [review]
the approval is unanimous.

**Review by wemitchell3 — APPROVED** [review]
Looks good to merge.

**Review by greenskybluephish — APPROVED** [review]

**Pull request merged**
