### PR TITLE
When the checkbox is clicked, the task element is removed from the DOM

### PR DESCRIPTION
**Pull request by SamBritt**
# Description

Because each task is marked incomplete (false) by default, they are displayed to the DOM. However,
once a user clicks any checkbox to mark the corresponding task as completed, a `PATCH` request is executed on that task, changing the value of `complete` inside our JSON server to `true`. In the `appendTasks()` function in`domAppender.js`, a conditional is executed, checking to see if each element returned from fetching the complete list of tasks has a value of `false`. If they do not, meaning `complete: true` or the task is completed, that task element is not displayed to the DOM.

Applies to issue # 2.2

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Testing Instructions

1. In terminal, run `git fetch`
2. `git checkout sb-patch-checkbox`
3. `cd` into `src/lib`
4. `grunt`
5. When the user submits a new task, the list of tasks plus the new task should be listed
along with checkboxes for each.
6. When a checkbox is clicked, the corresponding task should disappear from the DOM.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by greenskybluephish — DISMISSED** [review]
THATS A BIG 10/4 BUDDY

**Review by rosewisotzky — DISMISSED** [review]
don't forget those comments ol pal but otherwise she's doin' the thang

**Review by greenskybluephish — DISMISSED** [review]

**Review by greenskybluephish — DISMISSED** [review]
thats gonna be a yes from me dawg

**Review by rosewisotzky — APPROVED** [review]
GREAT JOB SAM PROUD OF U SON
-DAD

**Review by greenskybluephish — APPROVED** [review]
for reall approve

**Pull request merged**
