### PR TITLE
Update functionality for update button complete

### PR DESCRIPTION
**Pull request by SamBritt**
# Description

Added comments to code I created.
Added update logic to the 'update' button in the form opened by clicking the 'edit' button

Applies to issue # 2.3

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions
1. Open terminal
2. run `git fetch`
3. `git checkout sb-update-function`
4. `cd` into `src/lib`
5. run `grunt`
6. Add a new task, click on any edit button, enter in new values into the edit form, updated task should be replaced.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by wemitchell3 — DISMISSED** [review]
Tested. Works. Good to merge.

**Review by greenskybluephish — DISMISSED** [review]
apppproved

**Review by greenskybluephish — APPROVED** [review]
approved

**Review by wemitchell3 — APPROVED** [review]
Functionality works well. Good to merge.

**Pull request merged**
